#!/usr/bin/env sh
set -euo pipefail

if [ ! -d "${TMHOME}/config" ]; then

	echo "Running tendermint init to create configuration."
	/usr/bin/tendermint init

  sconfig -s ${TMHOME}/config/config.toml \
    proxy_app=${PROXY_APP:-kvstore} \
    moniker=${MONIKER:-dockernode} \
    consensus.timeout_commit=500ms \
    rpc.laddr=tcp://0.0.0.0:26657 \
    p2p.addr_book_strict=false \
    instrumentation.prometheus=true

  sconfig -s ${TMHOME}/config/genesis.json \
    chain_id=${CHAIN_ID:-dockerchain} \
    consensus_params.block.time_iota_ms=500

fi

exec /usr/bin/tendermint "$@"
