[env]
CONTAINER_NAME = "abci-test"
DOCKER_IMAGE = "informaldev/abci-harness:0.35.0"
HOST_RPC_PORT = 26657
CARGO_MAKE_WAIT_MILLISECONDS = 3500

# abci-test infrastructure:
# cargo make build-linux-abci  - build the ABCI app using Docker (helpful on a Mac)
# cargo make                   - run the test harness and all tests. Expects a Linux ABCI app already built.
# cargo make docker-up-debug   - troubleshoot the infra setup (useful to see docker error messages or the kvstore log).

[tasks.default]
clear = true
dependencies = [ "docker-up", "wait", "test", "docker-down" ]

[tasks.build-linux-abci]
command = "docker"
args = [ "run", "--rm", "--volume", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/..:/usr/src/myapp", "--workdir", "/usr/src/myapp", "rust:latest", "cargo", "build-abci" ]

[tasks.docker-down]
dependencies = [ "docker-stop", "docker-rm" ]

[tasks.docker-up]
command = "docker"
args = [
    "run",
    "--name", "${CONTAINER_NAME}",
    "--rm",
    "--publish", "26657:${HOST_RPC_PORT}",
    "--volume", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/../target/debug:/abci",
    "--detach",
    "${DOCKER_IMAGE}",
    "--verbose",
]
dependencies = ["docker-up-stop-old", "docker-up-rm-old"]

[tasks.docker-up-debug]
command = "docker"
args = ["run", "--name", "${CONTAINER_NAME}", "--rm", "--publish", "26657:${HOST_RPC_PORT}", "--volume", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/../target/debug:/abci", "${DOCKER_IMAGE}", "--verbose" ]
dependencies = ["docker-up-stop-old", "docker-up-rm-old"]

[tasks.test]
args = ["run", "--all-features", "--", "--verbose"]

[tasks.docker-stop]
command = "docker"
args = ["stop", "${CONTAINER_NAME}"]
ignore_errors = true
private = true

[tasks.docker-rm]
command = "docker"
args = ["rm", "--force", "${CONTAINER_NAME}"]
ignore_errors = true
private = true

[tasks.docker-up-stop-old]
alias = "docker-stop"

[tasks.docker-up-rm-old]
alias = "docker-rm"
